### ISSUE TITLE
Add message in Cart Widget 

### ISSUE THREAD

**Issue by joenilson** [nedac-sorbo/SyliusMinimumOrderValuePlugin#9]
The MinimumOrderValue message is only displayed in the Cart Summary, to avoid customer to leave the cart without bought, must be set a message in the widget warning about the minimum order value.

"Please complete thee minimum order value: %minimumOrderValue%".

**Comment by joenilson** [comment]
PR #10 waiting

**Comment by 4c0n** [comment]
@joenilson A few things:

1. We're not accepting new features, at least not until we can support the new release(s) of Sylius, we need to do some work on the tests for that.
2. You can just make this change in the overridden templates, so merging the PR has no real impact?
3. These kind of things need to be tested, so we'd like to see some Behat tests to confirm it actually works as expected.

I'll leave this open for now, so that perhaps we can have another look when the other things are sorted.
